### ISSUE TITLE
clustering gsdmm

### ISSUE THREAD

**Issue by federicoscabbia** [GianniBalistreri/happy_learning#30]
I cannot find examples on how to tune the hyper parameters of the gsdmm algorithm, could you halp me?

**Comment by GianniBalistreri** [comment]
You have to use one of the implemented evolutionary algorithm modules (SwarmIntelligence or GeneticAlgorithm). But first you have to preprocess your data set as follows:

1) Clean and tokenize text feature
2) Save preprocessed data set as CSV file

Then you can call and configure the optimization module. Here is an example using SwarmIntelligence:

from happy_learning.swarm_intelligence import SwarmIntelligence

_si: SwarmIntelligence = SwarmIntelligence(mode='model',
                                                   train_data_file_path=DATA_FILE_PATH_CLUSTER,
                                                   features=[TEXT_FEATURE],
                                                   re_populate=False,
                                                   models=['gsdmm'],
                                                   max_adjustments=2,
                                                   pop_size=10,
                                                   adjustment_rate=0.5,
                                                   adjustment_prob=0.85,
                                                   timer_in_seconds=43200,
                                                   plot=False,
                                                   output_file_path=OUTPUT_FILE_PATH
                                                   )
        _si.optimize()
